import { MovieSchema } from '../schemas/MovieSchema';

const movieHightlightsToo: MovieSchema[] = [
    {
        adult: false,
        backdrop_path: '/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
        genre_ids: [28, 35, 878],
        id: 533535,
        original_language: 'en',
        original_title: 'Deadpool & Wolverine',
        overview: 'A irresponsabilidade de Deadpool pode alterar a história do universo cinematográfico da Marvel.',
        popularity: 11393.026,
        poster_path: '/xq4v7JE8niZ75OYYPDGNn6Gzpyt.jpg',
        release_date: '2024-07-24',
        title: 'Deadpool & Wolverine',
        video: false,
        vote_average: 7.837,
        vote_count: 1805,
    },
    {
        adult: false,
        backdrop_path: '/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg',
        genre_ids: [16, 10751, 12, 35],
        id: 1022789,
        original_language: 'en',
        original_title: 'Inside Out 2',
        overview:
            'Na mente de Riley, recém-chegada à adolescência, o Quartel General é alvo de uma demolição súbita para dar espaço a algo totalmente inesperado: novas Emoções! A Alegria, a Tristeza, a Raiva, o Medo e a Repulsa, que têm feito, sem dúvida, uma boa gestão, não sabem como reagir à chegada da Ansiedade. E parece que ela não veio sozinha.',
        popularity: 3543.294,
        poster_path: '/9h2KgGXSmWigNTn3kQdEFFngj9i.jpg',
        release_date: '2024-06-11',
        title: 'Divertida-Mente 2 (Inside Out 2)',
        video: false,
        vote_average: 7.613,
        vote_count: 2358,
    },
    {
        adult: false,
        backdrop_path: '/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg',
        genre_ids: [16, 10751, 35, 28],
        id: 519182,
        original_language: 'en',
        original_title: 'Despicable Me 4',
        overview:
            'Gru, Lucy, as pequenas Margo, Edith, Agnes e bebé Gru Jr., que tem fortes intenções de atormentar o seu pai, enfrentam um novo vilão, Maxime Le Mal e a sua namorada Valentina, que obrigam a família a fugir.',
        popularity: 3195.72,
        poster_path: '/wISieKsABnOKgNlbNLuuMmIrhem.jpg',
        release_date: '2024-06-20',
        title: 'Gru - O Maldisposto 4',
        video: false,
        vote_average: 7.352,
        vote_count: 964,
    },
    {
        adult: false,
        backdrop_path: '/h2Qo9knqiotrgqg7efvFcJSqYuB.jpg',
        genre_ids: [16, 35, 12, 10751],
        id: 831815,
        original_language: 'en',
        original_title: 'Saving Bikini Bottom: The Sandy Cheeks Movie',
        overview:
            'Quando Bikini Bottom é retirado do oceano, a esquilo que adora ciência, Sandy Cheeks, e o amigo SpongeBob SquarePants viajam até ao Texas para salvarem a sua cidade.',
        popularity: 2042.706,
        poster_path: '/f2uhFiADjUFDHXpeUlw1lxgywMN.jpg',
        release_date: '2024-08-01',
        title: 'Salvar Bikini Bottom: O Filme da Sandy Cheeks',
        video: false,
        vote_average: 6.425,
        vote_count: 126,
    },
];

export default movieHightlightsToo;
